config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy, :show]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get 'mypage', to: 'users#show', as: 'mypage'

    resources :posts, only: [:new, :show, :index, :edit, :create, :destroy, :update] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users,only: [:show, :index, :edit, :update, :destroy]do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
    end
    resources :notifications, only: [:update]
    resources :chats, only: [:show, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post
  has_one :notification, as: :notifiable, dependent: :destroy

  validates :user_id, uniqueness: {scope: :post_id}

  after_create do
    create_notification(user_id: post.user_id)
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy  

  geocoded_by :address
  after_validation :geocode

  validates :title, :body, :image, :address, presence: true
  validates :title, length: { maximum: 20 }
  validates :body, length: { maximum: 160 }
  validate :validate_address


  def self.search(title)
   if title
     Post.where(['title LIKE?', "%#{title}%"])
   else
      Post.all
   end
  end


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def validate_address
      geocoded = Geocoder.search(address)
    unless geocoded&.first&.coordinates.present?
      errors.add(:address, 'が存在しません') 
    end
  end
  
  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  has_one :notification, as: :notifiable, dependent: :destroy

  validates :comment, presence: true
  validates :comment, length: { maximum: 160 }

  after_create do
    create_notification(user_id: post.user_id)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  has_many :notifications, as: :notifiable, dependent: :destroy

  after_create do
    notifications.create(user_id: followed.id)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 関連付け
  has_one_attached :profile_image
  has_many :post, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # バリデーション
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: { maximum: 20 }
  validates :bio, length: { maximum: 100 }

  # メソッド

  def self.search(name)
    if name
      User.where(['name LIKE?', "%#{name}%"])
    else
      User.all
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top], unless: :admin_controller?
  
  private
  
  def configure_authentication
    if admin_controller?
      authenticate_admin!
    else
      authenticate_user! unless action_is_public?
    end
  end
  
  def admin_controller?
    self.class.module_parent_name == 'Admin'
  end
  
  def action_is_public?
    controller_name == 'homes' && action_name == 'top'
  end
  
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_message(notification)
    case notification.notifiable_type
    when "Post"
      "#{notification.notifiable.user.name}さんが新規投稿しました"
    when "PostComment"
      "あなたの投稿が#{notification.notifiable.user.name}さんからコメントされました"
    when "Relationship"
      "#{notification.notifiable.follower.name}さんにフォローされました"
    else
      "あなたの投稿が#{notification.notifiable.user.name}さんにいいねされました"
    end
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/posts/edit.html.erb
<!--投稿編集-->
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">投稿編集</h5>
      <div class="form-body p-4">
        <% if @post.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post.errors.count %>件のエラーが発生しました
            </h6>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
          </div>
          <%= f.text_area :body, class: "form-control", rows: "3", placeholder: "本文" %>
          <hr>
          <%= f.submit '保存',class: "btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
        <p class="mt-2"><%= link_to "削除", post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-lg btn-block btn-danger" %></p>
      </div>
    </div>
  </div>
</div>

app/views/posts/new.html.erb
<!--新規投稿-->
<div class="container">
  <div class="row no-gutters">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto shadow-lg rounded px-0 my-5">
      <h5 class="text-dark bg-light p-4 mb-0">新規投稿</h5>
      <div class="form-body p-4">
        <% if @post.errors.any? %>
          <ul class="alert alert-danger" role="alert">
            <h6 class="alert-heading">
              <%= @post.errors.count %>件のエラーが発生しました
            </h6>
            <% @post.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>
        <%= form_with model: @post do |f| %>
          <%= f.file_field :image, accept: "image/*", class: "w-100" %>
          <div class="input-group mb-3 mt-4">
            <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
          </div>
          <%= f.text_area :body, class: "form-control", rows: "3", placeholder: "本文" %>
          <hr>
          <%= f.submit '投稿',class: "btn btn-lg btn-block btn-info mt-4" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<!--投稿詳細-->

<div class="card-list-container py-5">
  <div class="card w-50 mx-auto mt-4 shadow-lg">
    <%= image_tag @post.get_image(300, 300), class: "card-img-top"; %>
    <div class="card-body">
      <div class="row">
        <div class="col-2">
          <%= link_to user_path(@post.user.id) do %>
            <%= image_tag @post.user.get_profile_image(100, 100), class: "rounded-circle"; %>
          <% end %>
        </div>
        <div class="col-10">
          <p class="card-title">
            <%= link_to @post.title, post_path(@post.id), class: "text_dark"; %>
          </p>
          <p class="card-text"><%= @post.body %></p>
          <p>投稿日:<%= @post.created_at.strftime('%y/%m/%d') %></p>
          <span>By <%= @post.user.name %></span>
          <div>
            <p>コメント件数:<%= @post.post_comments.count %></p>
            <% @post.post_comments.each do |post_comment| %>
            <div class="row">
              <%= image_tag post_comment.user.get_profile_image(50, 50) %>
              <%= link_to post_comment.user.name, user_path(post_comment.user.id) %>
              <%= post_comment.comment %>
              <% if post_comment.user == current_user %>
                <%= link_to "削除", post_post_comment_path(post_comment.post, post_comment), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-sm btn-danger" %>
              <% end %>
            </div>
            <% end %>
          </div>

            <% if @post_comment.errors.any? %>
              <ul class="alert alert-danger" role="alert">
              <h6 class="alert-heading">
                <%= @post_comment.errors.count %>件のエラーが発生しました
              </h6>
                <% @post_comment.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            <% end %>

          <div class="form-body my-1">
            <%= form_with model: [@post, @post_comment] do |f| %>
            <div class="form-group">
              <%= f.text_area :comment, class: "form-control", placeholder: "コメント" %>
            <div class="text-right my-1">
              <%= f.submit "送信", class: "btn btn-sm btn-info" %>
            <% end %>
            </div>
            </div>
          </div>

          <% if @post.user == current_user %>
            <%= link_to "編集", edit_post_path(@post.id), class: "btn btn-block btn-success" %>
            <%= link_to "削除", post_path(@post), method: :delete, "data-confirm" => "本当に削除しますか？", class: "btn btn-block btn-danger" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>