config/routes.rb
Rails.application.routes.draw do

  devise_for :admin, skip: [:registrations, :password], controllers: {
    sessions: 'admin/sessions'
  }

  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy, :show]
  end

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end

  scope module: :public do
    devise_for :users
    root to: "homes#top"
    get 'mypage', to: 'users#show', as: 'mypage'

    resources :posts, only: [:new, :show, :index, :edit, :create, :destroy, :update] do
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
    end
    resources :users,only: [:show, :index, :edit, :update, :destroy]do
      member do
        get :favorites
      end
      resource :relationships, only: [:create, :destroy]
        get "followings" => "relationships#followings", as: "followings"
        get "followers" => "relationships#followers", as: "followers"
    end
    resources :notifications, only: [:update]
    resources :chats, only: [:show, :create, :destroy]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :user
  belongs_to :room

  validates :message, presence: true, length: { maximum: 140 }
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post
  has_one :notification, as: :notifiable, dependent: :destroy

  validates :user_id, uniqueness: {scope: :post_id}

  after_create do
    create_notification(user_id: post.user_id)
  end
end

app/models/notification.rb
class Notification < ApplicationRecord
  belongs_to :user
  belongs_to :notifiable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, as: :notifiable, dependent: :destroy  

  geocoded_by :address
  after_validation :geocode

  validates :title, :body, :image, :address, presence: true
  validates :title, length: { maximum: 20 }
  validates :body, length: { maximum: 160 }
  validate :validate_address


  def self.search(title)
   if title
     Post.where(['title LIKE?', "%#{title}%"])
   else
      Post.all
   end
  end


  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      image.variant(resize_to_limit: [width, height]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

  def validate_address
      geocoded = Geocoder.search(address)
    unless geocoded&.first&.coordinates.present?
      errors.add(:address, 'が存在しません') 
    end
  end
  
  after_create do
    user.followers.each do |follower|
      notifications.create(user_id: follower.id)
    end
  end
  
end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  has_one :notification, as: :notifiable, dependent: :destroy

  validates :comment, presence: true
  validates :comment, length: { maximum: 160 }

  after_create do
    create_notification(user_id: post.user_id)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

  has_many :notifications, as: :notifiable, dependent: :destroy

  after_create do
    notifications.create(user_id: followed.id)
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :user_rooms
  has_many :chats
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # 関連付け
  has_one_attached :profile_image
  has_many :post, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  # バリデーション
  validates :name, uniqueness: true
  validates :name, presence: true
  validates :name, length: { maximum: 20 }
  validates :bio, length: { maximum: 100 }

  # メソッド

  def self.search(name)
    if name
      User.where(['name LIKE?', "%#{name}%"])
    else
      User.all
    end
  end

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_square.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
      profile_image.variant(resize_to_limit: [width, height]).processed
  end

  def follow(user)
    active_relationships.create(followed_id: user.id)
  end

  def unfollow(user)
    active_relationships.find_by(followed_id: user.id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲストユーザー"
    end
  end

  def guest_user?
    email == GUEST_USER_EMAIL
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def notification_message(notification)
    case notification.notifiable_type
    when "Post"
      "#{notification.notifiable.user.name}さんが新規投稿しました"
    when "PostComment"
      "あなたの投稿が#{notification.notifiable.user.name}さんからコメントされました"
    when "Relationship"
      "#{notification.notifiable.follower.name}さんにフォローされました"
    else
      "あなたの投稿が#{notification.notifiable.user.name}さんにいいねされました"
    end
  end
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_errors_messages.html.erb
<% if model.errors.any? %>
  <ul class="alert alert-danger" role="alert">
    <h6 class="alert-heading">
      <%= model.errors.count %>件のエラーが発生しました
    </h6>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
  </ul>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Admin - OSHIDORI</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if admin_signed_in? %>
                <li>
                  <%= link_to '管理者ダッシュボード', admin_dashboards_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
                <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "管理者ログイン", new_admin_session_path, class: 'nav-link text-dark' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
      <% flash.each do |message_type, message| %>
        <div class="flash-message <%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-3 pb-2">
    </footer>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OSHIDORI</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV["GOOGLE_MAPS_API_KEY"] %>&libraries=places&callback=initialize"></script>
    <script src="https://kit.fontawesome.com/3224147d81.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <div class="navbar-brand">
            <%= link_to "OSHIDORI", root_path, class: 'nav-link text-dark' %>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
                <li class="nav-item">
                  <%= link_to "新規投稿", new_post_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "マイページ", mypage_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "全ての投稿", posts_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ユーザーリスト", users_path, class: 'nav-link text-dark' %>
                </li>
                <li class="dropdown">
                  <button class="btn btn-light dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    通知
                    <span class="badge badge-danger"><%= current_user.notifications.where(read: false).count %></span>
                  </button>
                  <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <% if current_user.notifications.where(read: false).any? %>
                      <small class="dropdown-item disabled">直近5件の未読の通知を表示しています</small>
                      <% current_user.notifications.where(read: false).limit(5).order(created_at: :desc).each do |notification| %>
                        <%= link_to notification_message(notification), notification_path(notification), method: :patch, class: "dropdown-item" %>
                      <% end %>
                    <% else %>
                      <span class="dropdown-item disabled">未読の通知はありません</span>
                    <% end %>
                  </div>
                </li>
                <li class="nav-item">
                  <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'nav-link text-dark' %>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to "新規登録", new_user_registration_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "ログイン", new_user_session_path, class: 'nav-link text-dark' %>
                </li>
                <li class="nav-item">
                  <%= link_to "管理者ログイン", new_admin_session_path, class: 'nav-link text-dark' %>
                </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
            <% flash.each do |message_type, message| %>
              <div class="flash-message <%= message_type %>"><%= message %></div>
            <% end %>

      <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-3 pb-2">
    </footer>
  </body>
</html>